[build]
builder = "NIXPACKS"
watchPatterns = ["/connector-service/**"]

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npm run start"
preDeployCommand = ["npm run build"]
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.multiRegionConfig."us-east4-eqdc4a"]
numReplicas = 1

[nixpacks]
aptPkgs = [
  "fontconfig",
  "fonts-dejavu-core",   
  "fonts-freefont-ttf",   
  "fonts-noto",          
  "fonts-noto-color-emoji"  
]