[build]
builder = "NIXPACKS"
watchPatterns = ["/bot-service/**"]

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "python main.py"
sleepApplication = false
multiRegionConfig = {"us-east4-eqdc4a":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10